const sectionTodo = document.querySelector(".section-todo")
console.log(sectionTodo.classList)
    // sectionTodo.classList.remove("container")
sectionTodo.classList.add("bg-dark")
console.log(sectionTodo.classList)
let value1 = sectionTodo.classList.contains("bg-dark")
console.log(value1)
sectionTodo.classList.remove("bg-dark")
console.log(sectionTodo.classList)
let value2 = sectionTodo.classList.contains("bg-dark")
console.log(value2)
console.log(sectionTodo.classList)