const navItems = document.getElementsByClassName("nav-item")
console.log(navItems)
console.log(navItems[0])
console.log(navItems[1])
console.log(navItems[2])
console.log(typeof navItems) // array like object (HTML Collections)