const navItems = document.querySelector(".nav-item")
console.log(navItems)
const navItemsAll = document.querySelectorAll(".nav-item")
console.log(navItemsAll)
console.log(typeof navItemsAll) // Array like objects (Node List)
console.log(navItemsAll[0])
console.log(navItemsAll[1])
console.log(navItemsAll[2])
const mainHeading = document.querySelector("#main-heading")
console.log(mainHeading)